23_01_2018_Uputnice_v2/RS1_Ispit/Controllers/UputnicaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ispit_2017_09_11_DotnetCore.EF;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RS1.Ispit.Web.Models;
using RS1_Ispit_asp.net_core.ViewModels;

namespace RS1_Ispit_asp.net_core.Controllers
{
    public class UputnicaController : Controller
    {
		MojContext _context;
		public UputnicaController(MojContext db)
		{
			_context = db;
		}
        public IActionResult Index()
        {
			UputnicaIndexVM model = new UputnicaIndexVM {
				Rows = _context.Uputnica.Select(x => new UputnicaIndexVM.Row {
					Uputio=x.DatumUputnice.ToString("dd.MM.yyyy")+" | Dr."+x.UputioLjekar.Ime,
					Pacijent=x.Pacijent.Ime,
					DatumEvidentiranja=x.DatumRezultata,
					UputnicaId=x.Id,
					VrstaPretrage=x.VrstaPretrage.Naziv
				}).ToList()

			};

			
            return View("Index",model);
        }
		public IActionResult Dodaj()
		{
			UputnicaDodajVM model = new UputnicaDodajVM();
			model.ljekari = _context.Ljekar.Select(x => new SelectListItem
			{
				Value=x.Id.ToString(),
				Text="Dr."+x.Ime
			}).ToList();
			model.pacijenti = _context.Pacijent.Select(x => new SelectListItem
			{
				Value = x.Id.ToString(),
				Text = x.Ime
			}).ToList();
			model.vrstePretrage = _context.VrstaPretrage.Select(x => new SelectListItem
			{
				Value = x.Id.ToString(),
				Text = x.Naziv
			}).ToList();
			
			
			return View("Dodaj", model);
		}

		public IActionResult Snimi(UputnicaDodajVM model)
		{
			if (!ModelState.IsValid)
			{
				model.ljekari = _context.Ljekar.Select(x => new SelectListItem
				{
					Value = x.Id.ToString(),
					Text = "Dr." + x.Ime
				}).ToList();
				model.pacijenti = _context.Pacijent.Select(x => new SelectListItem
				{
					Value = x.Id.ToString(),
					Text = x.Ime
				}).ToList();
				model.vrstePretrage = _context.VrstaPretrage.Select(x => new SelectListItem
				{
					Value = x.Id.ToString(),
					Text = x.Naziv
				}).ToList();

				return View("Dodaj", model);
			}

			Uputnica novaUputnica = new Uputnica()
			{
				PacijentId = model.pacijentId,
				UputioLjekarId = model.ljekarId,
				VrstaPretrageId = model.vrstaPretrageId,
				DatumUputnice = (DateTime)model.DatumUputnie
			};

			_context.Uputnica.Add(novaUputnica);
			_context.SaveChanges();
			List<RezultatPretrage> listaPretraga = _context.LabPretraga.Where(x => x.VrstaPretrageId == model.vrstaPretrageId).Select(x => new RezultatPretrage
			{
				LabPretragaId=x.Id,
				UputnicaId=novaUputnica.Id,
				ModalitetId=null,
				NumerickaVrijednost=null,

			}).ToList();

			_context.AddRange(listaPretraga);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		public IActionResult Detalji(int id)
		{
			UputnicaDetaljiVM model = _context.Uputnica.Where(x => x.Id == id).Select(x => new UputnicaDetaljiVM
			{
				DatumUputnice = x.DatumUputnice,
				DatumRezultata = x.DatumRezultata,
				Pacijent =x.Pacijent.Ime,
				UputnicaId=x.Id
			}).FirstOrDefault();
			return View("Detalji",model);
		}

		public IActionResult Zakljucaj(int id)
		{
			DateTime date = DateTime.Now; //kako trenutno vrijeme
										  // zasto kad koristim .Find(id) imam runtime
			Uputnica up = _context.Uputnica.Where(x => x.Id == id).FirstOrDefault();
			up.DatumRezultata = date;
			up.IsGotovNalaz = true;
			_context.Uputnica.Update(up);
			_context.SaveChanges();

			string idd = id.ToString();

			return Redirect("/Uputnica/Detalji?id=" + idd);
		}
	}
}

23_01_2018_Uputnice_v2/RS1_Ispit/Views/Uputnica/Detalji.cshtml
@using RS1_Ispit_asp.net_core.ViewModels
@{
    ViewData["Title"] = "Detalji";
}
@model UputnicaDetaljiVM
<h2>Podaci o uputnici (readonly)</h2>
<form>
	<div>
		<label>Datum uputnice: </label>
		<input type="text"  value="@Model.DatumUputnice.ToString("dd.MM.yyyy")" readonly />
	</div>
	<div>
		<label>Pacijent: </label>
		<input type="text"  value="@Model.Pacijent" readonly />
	</div>
	<div>
		<label>Datum rezultata: </label>
		<input type="text"  value="@Model.DatumRezultata" readonly/>
	</div>
	<div>
		<label>Zavrsen unos: </label>
		<a href="/Uputnica/Zakljucaj/?id=@Model.UputnicaId" class="btn btn-primary">Zakljucaj</a>
		<input type="text"  value="@Model.UputnicaId" hidden />
	</div>
</form>
<div id="div1"></div>
<script>
	$(document).ready(function (parameters) { 
		$.get("/RezultatiPretrage/Index?id=" +@Model.UputnicaId,function (rezultat, status) { 
			$("#div1").html(rezultat);
		});

	});


</script>

23_01_2018_Uputnice_v2/RS1_Ispit/Views/Uputnica/Dodaj.cshtml
@using RS1_Ispit_asp.net_core.ViewModels
@{
    ViewData["Title"] = "Dodaj";
}
@model UputnicaDodajVM
<h2>Nova uputnica</h2>

@*@if (!ModelState.IsValid)
{
<span class="alert-danger">
	@Html.ValidationSummary()
</span>
}*@
<form asp-action="Snimi" asp-controller="Uputnica" method="post">
	<div>
		<label>
			Uputio:
		</label>
		<select asp-items="@Model.ljekari" asp-for="@Model.ljekarId"></select>
	</div>
	<div>
		<label>Datum:</label>
		<input type="date" asp-for="@Model.DatumUputnie"required />
	</div>
	<div>
		<label>
			Pacijent:
		</label>
		<select asp-items="@Model.pacijenti" asp-for="@Model.pacijentId"></select>
	</div>
	<div>
		<label>
			Vrsta pretrage:
		</label>
		<select asp-items="@Model.vrstePretrage" asp-for="@Model.vrstaPretrageId"></select>
	</div>
	<input type="submit" value="Snimi" class="btn btn-primary"/>
</form>

23_01_2018_Uputnice_v2/RS1_Ispit/Views/Uputnica/Index.cshtml
@using RS1_Ispit_asp.net_core.ViewModels
@{
    ViewData["Title"] = "Index";
}
@model UputnicaIndexVM
<h2>Prikaz evidetiranih uputnica</h2>
<table class="table tab-content">
	<thead>
		<tr>
			<th>Uputio</th><th>Pacijent</th><th>Vrsta pretrage</th><th>Datum evidentiranja</th><th>Akcija</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var x in Model.Rows)
		{
		<tr>
			<td>@x.Uputio</td>
			<td>@x.Pacijent</td>
			<td>@x.VrstaPretrage</td>
			<td>@x.DatumEvidentiranja</td>
			<td><a href="/Uputnica/Detalji?id=@x.UputnicaId">Detalji</a></td>

		</tr>
		}
	</tbody>
</table>
<a href="/Uputnica/Dodaj" class="btn btn-primary">Dodaj </a>