15_02_2017_CASOVI_Autentifikacija/15_02_2017_PocetniProjekt_Autentifikacija/Ispit_2017_02_15/Models/OdrzaniCasDetalji.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ispit_2017_02_15.Models
{
    public class OdrzaniCasDetalji
    {
        public int Id { get; set; }
        public int OdrzaniCasId { get; set; }
        public virtual OdrzaniCas OdrzaniCas { get; set; }
        public int SlusaPredmetId { get; set; }
        public virtual SlusaPredmet SlusaPredmet { get; set; }
        public bool Prisutan { get; set; }
        public int BodoviNaCasu { get; set; }

    }
}

15_02_2017_CASOVI_Autentifikacija/15_02_2017_PocetniProjekt_Autentifikacija/Ispit_2017_02_15/Controllers/OdrzaniCasDetaljiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ispit_2017_02_15.EF;
using Ispit_2017_02_15.Models;
using Ispit_2017_02_15.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Ispit_2017_02_15.Controllers
{
    public class OdrzaniCasDetaljiController : Controller
    {
		MojContext _context;
		public OdrzaniCasDetaljiController(MojContext db)
		{
			_context = db;
		}
        public IActionResult Index(int id)
        {
			OdrzaniCasDetaljiIndexVM model = new OdrzaniCasDetaljiIndexVM {
				Rows=_context.OdrzaniCasDetalji.Where(x=>x.OdrzaniCasId==id).Select(x=>new OdrzaniCasDetaljiIndexVM.Row {
					Student = x.SlusaPredmet.UpisGodine.Student.Ime + " " + x.SlusaPredmet.UpisGodine.Student.Prezime,
					Prisutan = x.Prisutan,
					Bodovi=x.BodoviNaCasu,
					OdrzaniCasDetaljiId = x.Id
				}).ToList()
			};
            return PartialView("Index",model);
        }

		public IActionResult UcenikJePrisutan(int id)
		{
			OdrzaniCasDetalji casDetalji = _context.OdrzaniCasDetalji.Where(x => x.Id == id).FirstOrDefault();
			casDetalji.Prisutan = true;
			_context.OdrzaniCasDetalji.Update(casDetalji);
			_context.SaveChanges();
			return Redirect("/Cas/Uredi?id="+casDetalji.OdrzaniCasId);
		}

		public IActionResult UcenikJeOdsutan(int id)
		{
			OdrzaniCasDetalji casDetalji = _context.OdrzaniCasDetalji.Where(x => x.Id == id).FirstOrDefault();
			casDetalji.Prisutan = false;
			_context.OdrzaniCasDetalji.Update(casDetalji);
			_context.SaveChanges();
			return Redirect("/Cas/Uredi?id=" + casDetalji.OdrzaniCasId);

		}

		public IActionResult Uredi(int id)
		{
			OdrzaniCasDetaljiUrediVM model = _context.OdrzaniCasDetalji.Where(x => x.Id == id).Select(x => new OdrzaniCasDetaljiUrediVM {
				Student=x.SlusaPredmet.UpisGodine.Student.Ime+" "+ x.SlusaPredmet.UpisGodine.Student.Prezime,
				Bodovi=x.BodoviNaCasu,
				OdrzaniCasDetaljiId=x.Id,
				CasId=x.OdrzaniCasId
			}).FirstOrDefault();

			return PartialView("Uredi", model);

		}

		public IActionResult SnimiPromjene(OdrzaniCasDetaljiUrediVM model)
		{
			if (!ModelState.IsValid)
			{
				return View("/Uredi/Index", model);
			}
			OdrzaniCasDetalji casDetalji = _context.OdrzaniCasDetalji.Where(x => x.Id == model.OdrzaniCasDetaljiId).FirstOrDefault();
			casDetalji.BodoviNaCasu = model.Bodovi;
			_context.OdrzaniCasDetalji.Update(casDetalji);
			_context.SaveChanges();

			return Redirect("/Cas/Uredi?id="+model.CasId);
		}
	}
}

15_02_2017_CASOVI_Autentifikacija/15_02_2017_PocetniProjekt_Autentifikacija/Ispit_2017_02_15/Views/OdrzaniCasDetalji/Index.cshtml
@using Ispit_2017_02_15.ViewModels
@{
    ViewData["Title"] = "Index";
}
@model OdrzaniCasDetaljiIndexVM
<h2></h2>
<table class="table tab-content">
	<thead><tr>
	<th>Student</th>
	<th>Bodovi</th>
	<th>Prisutan</th>
	<th>Akcija</th>
</tr>
	</thead>
	<tbody>
		
			@foreach (var x in Model.Rows)
			{<tr>

	<td>@x.Student</td>
	<td>@x.Bodovi</td>
	@if (x.Prisutan == false)
	{
		<td><a href="/OdrzaniCasDetalji/UcenikJePrisutan?id=@x.OdrzaniCasDetaljiId" class="btn-danger">Odustan</a></td>
	}
	else
	{
		<td><a href="/OdrzaniCasDetalji/UcenikJeOdsutan?id=@x.OdrzaniCasDetaljiId" class="btn-success">Prisutan</a></td>
	}
	@if (x.Prisutan == true)
	{
		<td><a class="aKlik1" atribut="@x.OdrzaniCasDetaljiId">Uredi</a></td>
	}

	<td></td>
</tr>
}
	</tbody>
</table>
<script>
	$(document).ready(function (parameters) {
		$(".aKlik1").click(function (event) {
			var btn = $(this);
			var id = btn.attr("atribut");
			$.get("/OdrzaniCasDetalji/Uredi?id=" + id,function (rezultat, status) {
			$("#div1").html(rezultat);
		 });

		});


	 });
</script>

15_02_2017_CASOVI_Autentifikacija/15_02_2017_PocetniProjekt_Autentifikacija/Ispit_2017_02_15/Views/OdrzaniCasDetalji/Uredi.cshtml
@using Ispit_2017_02_15.ViewModels
@{
	ViewData["Title"] = "Uredi";
}
@model OdrzaniCasDetaljiUrediVM
<h2></h2>
<form asp-action="SnimiPromjene" asp-controller="OdrzaniCasDetalji">
	<div>
		<label>Student:</label>
		<input type="text" asp-for="@Model.Student" value="@Model.Student" readonly />
	</div>
	<div>
		<label>Bodovi:</label>
		<input type="text" asp-for="@Model.Bodovi" value="@Model.Bodovi" />
	</div>
	<input type="text" asp-for="@Model.CasId" value="@Model.CasId"  />
	<input type="text" asp-for="@Model.OdrzaniCasDetaljiId" value="@Model.OdrzaniCasDetaljiId"  />
	<input type="submit" value="Snimi promjene" class="btn btn-primary" />
</form>