24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Models/Angazovan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_PrakticniDioIspita_2017_01_24.Models
{
    public class Angazovan
    {
        public int Id { get; set; }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Models/Nastavnik.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_PrakticniDioIspita_2017_01_24.Models
{
    public class Nastavnik
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Ime { get; set; }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Models/Odjeljenje.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_PrakticniDioIspita_2017_01_24.Models
{
    public class Odjeljenje
    {
        public int Id { get; set; }
        public string Oznaka { get; set; }
        public int Razred { get; set; }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Models/OdrzaniCas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_PrakticniDioIspita_2017_01_24.Models
{
    public class OdrzaniCas
    {
        public int Id { get; set; }
        public DateTime datum { get; set; }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Models/OdrzaniCasDetalj.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_PrakticniDioIspita_2017_01_24.Models
{
    public class OdrzaniCasDetalj
    {
        public int Id { get; set; }
        public bool Odsutan { get; set; }
        public int? Ocjena { get; set; }
        public bool? OpravdanoOdsutan { get; set; }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Models/Predmet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_PrakticniDioIspita_2017_01_24.Models
{
    public class Predmet
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Models/Ucenik.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_PrakticniDioIspita_2017_01_24.Models
{
    public class Ucenik
    {
        public int Id { get; set; }
        public string Ime { get; set; }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Models/UpisUOdjeljenje.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_PrakticniDioIspita_2017_01_24.Models
{
    public class UpisUOdjeljenje
    {
        public int Id { get; set; }
        public int BrojUDnevniku { get; set; }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/ViewModels/OdrzaniCasIndexVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RS1_PrakticniDioIspita_2017_01_24.ViewModels
{
    public class OdrzaniCasIndexVM
    {
		public List<Row> Rows { get; set; }
		public class Row {
			public DateTime Datum  { get; set; }
			public string odjeljenje { get; set; }
			public string Predmet { get; set; }
			public int OdrzaniCasId { get; set; }

		}
	}
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Controllers/AjaxTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RS1_PrakticniDioIspita_2017_01_24.Controllers
{
    public class AjaxTestController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult AjaxTestAction()
        {
            return PartialView("_AjaxTestView");
        }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RS1_PrakticniDioIspita_2017_01_24.Models;

namespace RS1_PrakticniDioIspita_2017_01_24.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Controllers/OdrzaniCasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RS1_PrakticniDioIspita_2017_01_24.EF;
using RS1_PrakticniDioIspita_2017_01_24.ViewModels;

namespace RS1_PrakticniDioIspita_2017_01_24.Controllers
{
    public class OdrzaniCasController : Controller
    {
		MojContext _context;
		public OdrzaniCasController(MojContext db)
		{
			_context = db;
		}
        public IActionResult Index()
        {
			
            return View();
        }
    }
}

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h2>Home/Index</h2>
<h2>Dobro došli</h2>

<br />
@Html.ActionLink("Ajax text", "Index", "AjaxTest")
<br />
@Html.ActionLink("CasoviController/Index", "Index", "Casovi")  << -- Potrebno implementirati!

24_01_2017_PocetniProjekt/RS1_PrakticniDioIspita_2017_01_24/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ispit_2017_09_11_DotnetCore</title>

    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="/css/site.css" />


    <script src="/lib/jquery/dist/jquery.js"></script>
    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="/js/site.js"></script>
    <script src="/JFIT.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Ispit_2017_09_11_DotnetCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Casovi" asp-action="Index">Casovi</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Ispit_2017_09_11_DotnetCore</p>
        </footer>
    </div>
</body>
</html>